#!/usr/bin/env perl
# Originally written by Norbert Preining, 2017.  Public domain.
# 
# Test various files on their "usability" or "loadability"
#
# Ideas:
# - tlpobj contains
#       testfile ....tex
#       reference ....pdf
# later: auto generation
# - .cls        =>      test with pdflatex and compare pdfs
# - .sty        =>      load in article or some other class?
#
# functionality:
#   scriptname check [-all] | <pkg> ...        
#       checks all/passed packages
#   scriptname rebuild [-all] | <pkg> ...
#       rebuilds reference file for all/passed packages
#
# further arguments:
#  --basedir BASE    location of files: BASE/<pkg>/...
#  --master MASTER   location of Master tree
#                    (root of an installation containing tlpkg)
#
#
# TODO
# * fix layout of BASE/...
#
# Future ideas:
# * provide CTAN package for building reference pdf and
#   submitting it to TeX Live together with a test file
#

my $Master;

BEGIN {
  $^W = 1;
  $| = 1;
  (my $mydir = $0) =~ s,/[^/]*$,,;
  if ($mydir eq $0) {
    $mydir = ".";
  }
  #my $tlroot = "$mydir/../..";
  my $tlroot = "$mydir";
  unshift (@INC, "$tlroot/tlpkg");
  #chomp ($Master = `cd $mydir/../.. && pwd`);
  chomp ($Master = `pwd`);
}

use File::Find;
use Getopt::Long;
use Pod::Usage;

use TeXLive::TLPDB;
use TeXLive::TLConfig;
use TeXLive::TLUtils qw(info debug ddebug debug_hash tlwarn tldie);

my $prg = TeXLive::TLUtils::basename($0);

my $opt_basedir = "/home/norbert/Development/TeX/tltesting.git/testfiles";
my $opt_help = 0;
my $opt_version = 0;
my $opt_all = 0;

TeXLive::TLUtils::process_logging_options ();
GetOptions (
  "base=s"     => \$opt_basedir,
  "all|a"      => \$opt_all,
  "version"    => \$opt_version,
  "help|?"     => \$help) || pod2usage(1);

pod2usage ("-exitstatus" => 0, "-verbose" => 2) if $help;
if ($opt_version) { print "dev\n"; exit 0; } 

#
if ($opt_all) { die("option -all is not implemented by now!"); }

#
# we want to setup the master that we are running all tests
# with our own programs
$::installerdir = $Master;  # TLUtils.pm should be smarter
$ENV{'PATH'} = "$Master/bin/" . TeXLive::TLUtils::platform() . ":$ENV{PATH}";

exit (&main());


sub main {
  # no interference from TEXMFHOME, etc.
  $ENV{'TEXMFHOME'}   = "/nonesuch-home";
  $ENV{'TEXMFVAR'}    = "/nonesuch-uvar";
  $ENV{'TEXMFCONFIG'} = "/nonesuch-config";
  $ENV{'TEXMFLOCAL'}  = "/nonesuch-local";

  # load TLPDB
  my $tlpdb = TeXLive::TLPDB->new("root" => $Master);
  die "cannot find tlpdb in $Master" unless defined($tlpdb);

  #
  my $cmd = shift @ARGV;
  die("No command passed") if (!$cmd);
      

  # setup packages to check:
  my @packs = @ARGV;

  my $ret = 0;
  if ($cmd eq "check" || $cmd eq "rebuild") {
    for my $p (@packs) {
      $ret += check_rebuild_package($cmd, $p);
    }
  } else {
    die("unknown command: $cmd");
  }
  exit($ret);
}


# check or rebuild reference for one package
sub check_rebuild_package {
  my ($cmd, $p) = @_;
  die "NOT IMPLEMENTED";
}



__END__

=head1 NAME

check-package - check package for usability

=head1 SYNOPSIS

check-package check|rebuild [I<option>]... [I<pkg>]

=head1 OPTIONS


The standard options B<-q>, B<-v>, and B<-logfile>=I<file> are also
accepted; see the C<process_logging_options> function in
L<TeXLive::TLUtils> for details.  In particular, with B<-v> or higher,
the packages found to be needed for each I<engine.format> combination
will be reported.

=head1 DESCRIPTION


=head1 AUTHORS AND COPYRIGHT

This script and its documentation were written for the TeX Live
distribution (L<http://tug.org/texlive>) and both are licensed under the
GNU General Public License Version 2 or later.

=cut

# Local Variables:
# perl-indent-level: 2
# tab-width: 2
# indent-tabs-mode: nil
# End:
# vim: sw=2 expandtab
